### ISSUE TITLE
Setup and run Nutberry node for Habitat on mainnet

### ISSUE THREAD

**Issue by IlluminatedUnicorn** [acebusters/AIPs#277]
# Bounty

## Scope
- Prepare a platform for running a habitat node
- Install and run the node
- Make node accessible from outside world
- Keep node running (while needed)

## Deliverables
- Running and accessible Nutberry node (URL)

## Funding Circle
LeapDAO

## Bounty Owner/Gardener
@eshavkun 

## Roles
bounty gardener&worker: @eshavkun / 470 DAI 
bounty reviewer: @pinkiebell  / 80 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by IlluminatedUnicorn** [comment]
The node is running on R Pi with Nutberry being behind nginx server. Node URL is https://habitat-pi.duckdns.org
Example RPC call:
`curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method":"eth_blockNumber","id":1}' https://habitat-pi.duckdns.org`
@zschavi Can you please review

**Comment by pinkiebell** [comment]
LGTM 🎉
